### PR TITLE
fix: Incorrect identification of source IP addresses

### PR DESCRIPTION
**Pull request by CorrectRoadH**
to fix https://github.com/IceWhaleTech/CasaOS/security/advisories/GHSA-32h8-rgcj-2g3c#event-102885

API V1 and V2 both read ip from the request header. So the fix is effective for v1 and v2.

### CODE REVIEW

**Comment by CorrectRoadH** [comment]
@tigerinus Please take a look

**Comment by LinkLeong** [comment]
Need to re-determine the authentication issues, not to do the consolidation for now.

**Comment by tigerinus** [comment]
Discussed with @LinkLeong - let's try to get this PR merged (with enough testing).

In future, we will try to bring this JWT validating to CasaOS-Gateway, and apply a different authentication mechanism in each CasaOS module - not for now.

**Comment by tigerinus** [comment]
@CorrectRoadH - let's continue to collaborate this fix at https://github.com/IceWhaleTech/CasaOS-Gateway/security/advisories/GHSA-vjh7-5r6x-xh6g

Please confirm that you can work in the temporary private fork (see new advisory link) as soon as possible. Once you've confirmed it's working, please remove this PR, its branch and all information that's public.

**Pull request closed without merging**
